version: 1.0.0
services:
  - mysql

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
              - composer install --ansi
              - source ${BLT_DIR}/scripts/pipelines/setup_env
        - validate:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/validate
        - setup-app:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/setup_app
        # Execute all testing and validation tasks.
        - run-tests:
            type: script
            script:
              - cd $BUILD_DIR/docroot
              - ../vendor/bin/drush runserver --default-server=builtin 8080 &>/dev/null &
              - ../vendor/bin/phantomjs --webdriver=4444 > /dev/null &
              - sleep 10
              # Run a specific Lightning test:
              # - Panelizer is enabled for landing pages (1e244c89)
              - ../vendor/bin/behat --config ./sites/default/files/behat.yml --tags=1e244c89
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
        - deploy:
            script:
              - pipelines-deploy
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pre-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy